---
- name: Checking ssh directory
  stat:
    path: "{{ ssh_config.destination }}"
  register: ssh_config_dir
  changed_when: false

- name: Create ssh config directory
  file:
    path: "{{ ssh_config.destination }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0700"
  when: not ssh_config_dir.stat.exists

- name: Configure the users ssh config file
  template:
    src: "config.j2"
    dest: "{{ ssh_config.destination }}/config"
    owner: "{{ ansible_user_id }}"
    mode: "0600"
  when: ssh_config.config

- name: Configure private key
  template:
    src: "private.j2"
    dest: "{{ ssh_config.destination }}/id"
    owner: "{{ ansible_user_id }}"
    mode: "0600"
  when: secrets.ssh.private

- name: Configure public key
  template:
    src: "public.j2"
    dest: "{{ ssh_config.destination }}/id.pub"
    owner: "{{ ansible_user_id }}"
    mode: "0600"
  when: secrets.ssh.private
