---
- name: Checking ssh directory
  stat:
    path: "{{ ansible_ssh_config.destination }}"
  register: ssh_config_dir
  changed_when: false

- name: Create ssh config directory
  file:
    path: "{{ ansible_ssh_config.destination }}"
    state: directory
    owner: "{{ ansible_ssh_config.owner.name }}"
    group: "{{ ansible_ssh_config.owner.group }}"
    mode: "0700"
  when: not ssh_config_dir.stat.exists

- name: Configure the users ssh config file
  template:
    src: "config.j2"
    dest: "{{ ansible_ssh_config.destination }}/config"
    owner: "{{ ansible_ssh_config.owner.name }}"
    group: "{{ ansible_ssh_config.owner.group }}"
    mode: "0600"
  when: ansible_ssh_config.config