---
- name: Configure private key
  template:
    src: "private.j2"
    dest: "{{ ansible_ssh_config.destination }}/{{ item.prefix }}"
    owner: "{{ ansible_ssh_config.owner.name }}"
    group: "{{ ansible_ssh_config.owner.group }}"
    mode: "0600"
  when: item.private

- name: Configure public key
  template:
    src: "public.j2"
    dest: "{{ ansible_ssh_config.destination }}/{{ item.prefix }}.pub"
    owner: "{{ ansible_ssh_config.owner.name }}"
    group: "{{ ansible_ssh_config.owner.group }}"
    mode: "0600"
  when: item.public