---
- debug:
    msg: "{{ vars[(role_path | basename).split('.')[-1].replace('-','_')] }}"
  when: DEBUG | d() | bool

- include_tasks: configure.yml
- include: keys.yml
  with_items: "{{ ansible_ssh_config.sshkeys }}"